### PR TITLE
Git Tutorial

### PR DESCRIPTION
**Pull request by SoraShu**

### CODE REVIEW

**Comment by eastonman** [comment]
why autocorrect is complaining?

**Comment by shirok1** [comment]
> why autocorrect is complaining?

image

Trailing space

**Comment by shirok1** [comment]
Forget that

image

**Comment by shirok1** [comment]
I suggest adopting https://github.com/huacnlee/autocorrect-action#enable-reviewdog-for-report

**Comment by SoraShu** [comment]
image

分支示意图

**Comment by eastonman** [comment]
Check the typo in `.gitignore`, apart from this LGTM.

**Review by eastonman — APPROVED** [review]

**Pull request merged**
